#noun = input("Enter an animal:")
#noun2 = input("Enter another animal:")
#noun3 = input("Enter an object:")
#print("The " + noun + " and the " + noun2 + " went to find the " + noun3)

pnoun = input('Choose a plural noun:')
fic = input('Choose a fictional character:')
occ = input('Choose an occupation:')
pl = input('Choose a place:')
n = input('Choose a number:')
adj = input('Choose an adjective:')
vrb = input("Choose a verb ending in '-ing':")
pnoun2 = input('Choose another plural noun:')
pl2 = input('Choose another place:')
adj2 = input('Choose another adjective:')
pnoun3 = input('Choose another plural noun:')
vrb2 = input("Choose another verb ending in '-ing':")
pnoun4 = input('Choose another plural noun:')
adj3 = input('Choose another adjective:')
noun = input('Choose a noun:')
bpart = input('Choose a part of the body:')
verb = input('Choose a verb:')
adj4 = input('Choose yet another adjective...')
bpart2 = input('FINALLY! Choose another part of the body:')

print('Hello, my fellow ' + pnoun + ". It's the year 1969 of our lord and savior " + fic + ', and I am George Washington, the first ' + occ + '.')
print('I am writing from (the) ' + pl + ', where I have been living in secret for the past ' + n + ' years.')
print('I am concerned by the ' + adj + ' state of affairs in America these days; It seems as if your politicians are more concerned with ' + vrb + ' one another than listening to the ' + pnoun2 + ' of the people.')
print('When we declared our independence from (the) ' + pl2 + ', we set forth on a/an ' + adj2 + ' path guided by the voices of the everyday ' + pnoun3 + '.')
print('If we are going to keep ' + vrb2 + ', then we need to learn how to respect all ' + pnoun4 + '.')
print("Don't get me wrong; we had " + adj3 + ' problems in my day, too.')
print('Benjamin Franklin once called me a/an ' + noun + ' and kicked me in the ' + bpart + '.')
print('But at the end of the day, we were able to ' + verb + ' in harmony.')
print('Let us find that ' + adj4 + ' spirit once again, or else I am taking my ' + bpart2 + ' off of the quarter, you lil mfs...')
